control_move_ptz:
  fields:
    entity_id:
      required: true
      example: "camera.imou_living_room"
      selector:
        selector:
          entity:
            integration: imou_life
            domain: button
      duration:
        required: true
        example: 500
        default: 500
        selector:
          number:
            min: 100
            max: 5000
            unit_of_measurement: "ms"