control_move_ptz:
  target:
    entity:
      domain: button
      integration: imou_life
  fields:
    duration:
      required: false
      default: 500
      example: 500
      selector:
        number:
          min: 100
          max: 10000
          unit_of_measurement: ms
