control_move_ptz:
  fields:
    entity_id:
      required: true
      example: "camera.imou_living_room"
      selector:
        text: {}
      operation:
        required: true
        example: 0
        default: 1
        selector:
          number:
            min: 0
            max: 3
      duration:
        required: true
        example: 500
        default: 500
        selector:
          number:
            min: 100
            max: 5000
            unit_of_measurement: "ms"