control_move_ptz:
  target:
    entity:
      integration: imou_life
      domain: button
  fields:
    duration:
      required: true
      example: 500
      default: 500
      selector:
        number:
          min: 100
          max: 5000
          unit_of_measurement: "ms"