control_move_ptz:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          domain: button
          integration: imou_life
    duration:
      required: true
      selector:
        number:
          min: 100
          max: 5000